In [1]:
# #5. A survey was conducted among 2800 customers on several demographic characteristics. 
# Working status, sex, age, age-group, race, happiness, no. of child, marital status, educational qualifications, 
# income group etc. had been captured for that purpose. (Data set: sample_survey.csv).

# a. Is there any relationship in between labour force status with marital status?
# b. Do you think educational qualification is somehow controlling the marital status?
# c. Is happiness is driven by earnings or marital status?

In [2]:
import numpy as np
import pandas as pd
import scipy.stats as stats

surveyDF = pd.read_csv("sample_survey.csv")
surveyDF.head()

id            wrkstat        marital  childs   age  educ  paeduc  maeduc  \
0   1  Working full time       Divorced     2.0  60.0  12.0    12.0    12.0   
1   2  Working part-time  Never married     0.0  27.0  17.0    20.0     NaN   
2   3  Working full time        Married     2.0  36.0  12.0    12.0    12.0   
3   4  Working full time  Never married     0.0  21.0  13.0     NaN    12.0   
4   5  Working full time  Never married     0.0  35.0  16.0     NaN    12.0   

   speduc          degree  ...        agecat childcat news1 news2  news3  \
0     NaN     High school  ...      55 to 64      1-2    No    No     No   
1     NaN  Junior college  ...      25 to 34     None    No    No    Yes   
2    16.0     High school  ...      35 to 44      1-2    No    No     No   
3     NaN     High school  ...  Less than 25     None    No    No     No   
4     NaN        Bachelor  ...      35 to 44     None    No    No     No   

  news4 news5      car1      car2      car3  
0    No    No  American  Japanese  Japanese  
1    No    No  American    German  Japanese  
2   Yes   Yes  American  American       NaN  
3   Yes   Yes  American     Other       NaN  
4    No    No  American  American    Korean  

[5 rows x 46 columns]

In [3]:
##Step 1: Checking if sample truly represents the population or not::
#Yes


##Step 2: Defining Null & Alt Hypothesis::
#Null hypothesis: There is no relationship between categorical variables.
#Alt hypothesis: There is a relationship between categorical variables.


##Step 3: Will decide what test to be done, based on the data::
#Chi-Square: Influence of one categorical variable on another

In [4]:
##Step 4: Will calculate the test statistic – it will be the Program Output::
# a. Is there any relationship in between labour force status with marital status?
wrkstat_marital_xtab = pd.crosstab(surveyDF.wrkstat,surveyDF.marital,margins=True)
a = stats.chi2_contingency(observed=wrkstat_marital_xtab)
print(a)

(729.2421426572284, 1.820339965538765e-127, 40, array([[5.16918728e+01, 1.55886926e+02, 7.68424028e+01, 1.07787986e+01,
        3.28000000e+01, 3.28000000e+02],
       [8.51024735e+00, 2.56643110e+01, 1.26508834e+01, 1.77455830e+00,
        5.40000000e+00, 5.40000000e+01],
       [6.20932862e+01, 1.87254417e+02, 9.23045936e+01, 1.29477032e+01,
        3.94000000e+01, 3.94000000e+02],
       [1.24501767e+01, 3.75459364e+01, 1.85077739e+01, 2.59611307e+00,
        7.90000000e+00, 7.90000000e+01],
       [7.24946996e+00, 2.18621908e+01, 1.07766784e+01, 1.51166078e+00,
        4.60000000e+00, 4.60000000e+01],
       [9.14063604e+00, 2.75653710e+01, 1.35879859e+01, 1.90600707e+00,
        5.80000000e+00, 5.80000000e+01],
       [2.46954770e+02, 7.44740283e+02, 3.67109894e+02, 5.14950530e+01,
        1.56700000e+02, 1.56700000e+03],
       [4.79095406e+01, 1.44480565e+02, 7.12197880e+01, 9.99010601e+00,
        3.04000000e+01, 3.04000000e+02],
       [4.46000000e+02, 1.34500000e+03, 6.630000

In [5]:
# b. Do you think educational qualification is somehow controlling the marital status?
degree_marital_xtab = pd.crosstab(surveyDF.degree,surveyDF.marital,margins=True)
b = stats.chi2_contingency(observed=degree_marital_xtab)
display(b)

(122.68449020508541,
 7.424404099753273e-15,
 25,
 array([[  75.06345268,  227.39312301,  111.83268345,   15.75824176,
           47.95249911,  478.        ],
        [  32.19248493,   97.52215526,   47.9617157 ,    6.75824176,
           20.56540234,  205.        ],
        [ 235.55476781,  713.57674583,  350.9393832 ,   49.45054945,
          150.4785537 , 1500.        ],
        [  32.66359447,   98.94930876,   48.66359447,    6.85714286,
           20.86635945,  208.        ],
        [  67.52570011,  204.55866714,  100.60262318,   14.17582418,
           43.1371854 ,  430.        ],
        [ 443.        , 1342.        ,  660.        ,   93.        ,
          283.        , 2821.        ]]))

In [6]:
# c. Is happiness driven by earnings or marital status?
happy_income_xtab = pd.crosstab(surveyDF.happy,surveyDF.income,margins=True)
c1 = stats.chi2_contingency(observed=happy_income_xtab)
display(c1)

(178.95053061216427,
 7.234749067043371e-21,
 36,
 array([[   3.89520355,   23.12777106,   21.66706973,   29.82265216,
          191.35187424,    2.92140266,    3.89520355,    4.26037888,
            4.01692866,    5.72108021,    7.06005643,    4.26037888,
          302.        ],
        [  18.16041919,  107.82748892,  101.01733172,  139.04070939,
          892.1305925 ,   13.62031439,   18.16041919,   19.86295848,
           18.72793229,   26.67311568,   32.91575977,   19.86295848,
         1408.        ],
        [   9.94437727,   59.04474002,   55.31559855,   76.13663845,
          488.51753325,    7.45828295,    9.94437727,   10.87666264,
           10.25513906,   14.60580411,   18.0241838 ,   10.87666264,
          771.        ],
        [  32.        ,  190.        ,  178.        ,  245.        ,
         1572.        ,   24.        ,   32.        ,   35.        ,
           33.        ,   47.        ,   58.        ,   35.        ,
         2481.        ]]))

In [7]:
happy_marital_xtab = pd.crosstab(surveyDF.happy,surveyDF.marital,margins=True)
c2 = stats.chi2_contingency(observed=happy_marital_xtab)
display(c2)


(260.68943894182826,
 7.762777322980048e-47,
 15,
 array([[  53.6969697 ,  162.06060606,   79.27272727,   11.15151515,
           33.81818182,  340.        ],
        [ 248.58538324,  750.24527629,  366.98609626,   51.62495544,
          156.55828877, 1574.        ],
        [ 140.71764706,  424.69411765,  207.74117647,   29.22352941,
           88.62352941,  891.        ],
        [ 443.        , 1337.        ,  654.        ,   92.        ,
          279.        , 2805.        ]]))

In [8]:
##Step 5: Final conclusion based on p-value::
##Conclusion ::
print('Conclusion: a. Since 1.82e-127 < 0.05 , the p-value rejects H0, will conclude that there is a significant influence.')
print('Conclusion: b. Since 7.4e-15 < 0.05 , the p-value rejects H0, will conclude that there is a significant influence.')
print('Conclusion: c1. Since 7.2e-21 < 0.05 , the p-value rejects H0, will conclude that there is a significant influence.')
print('Conclusion: c2 Since 7.7e-47 < 0.05 , the p-value rejects H0, will conclude that there is a significant influence.')

Conclusion: a. Since 1.82e-127 < 0.05 , the p-value rejects H0, will conclude that there is a significant influence.
Conclusion: b. Since 7.4e-15 < 0.05 , the p-value rejects H0, will conclude that there is a significant influence.
Conclusion: c1. Since 7.2e-21 < 0.05 , the p-value rejects H0, will conclude that there is a significant influence.
Conclusion: c2 Since 7.7e-47 < 0.05 , the p-value rejects H0, will conclude that there is a significant influence.
