In [3]:
#Loading the MNIST dataset in keras
from __future__ import print_function
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D
from keras import backend as k

In [5]:
batch_size = 128
num_classes = 10
epochs = 3

#input image dimensions
img_rows, img_cols = 28, 28 #We already know the dimension of each image of mnist is of 28*28. That's why we have taken 28*28
                            ##matrix here

In [7]:
#The data split between train & test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()
display(x_train)
display(y_train)
display(x_test)
display(y_test)

display(x_train.shape)
display(y_train.shape)
display(x_test.shape)
display(y_test.shape)

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

(60000, 28, 28)

(60000,)

(10000, 28, 28)

(10000,)

In [8]:
#Now, will reshape them. Why - To modify their shape from 2D to 3D

##Let's first verify if it's a B/W or a colored image
x_train = x_train.reshape(x_train.shape[0],img_rows,img_cols,1)
x_test = x_test.reshape(x_test.shape[0],img_rows,img_cols,1)
input_shape = (img_rows, img_cols,1)

input_shape

(28, 28, 1)

In [9]:
x_train = x_train.astype('float32') #Converting from int to float. But why? - To rormalize the data between 0 & 1.
x_test = x_test.astype('float32')

x_train/=255 #Dividing by 255. But why? - To normalize the data between 0 & 1
x_test/=255

In [12]:
display('x_train shape',x_train.shape)
display(x_train.shape[0],'train samples')
display(x_test.shape[0],'test samples')

'x_train shape'

(60000, 28, 28, 1)

60000

'train samples'

10000

'test samples'

In [13]:
display(y_train[0])
display(y_test[0])

5

7

In [14]:
#Converting class vectors to binary (Categorical) class metrices
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

display(y_train[0])
display(y_test[0])

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [15]:
#Model Initialization
model = Sequential() #Initialization of network - InputLayer
model.add(Conv2D(32,kernel_size=(3,3),activation = 'relu', input_shape = input_shape)) #Convolution layer 1 - 28*28 size
model.add(Conv2D(64,(3,3),activation='relu')) #Convolution Layer 2
model.add(MaxPooling2D(pool_size=(2,2))) #Pooling layer
model.add(Dropout(0.25)) #Dropout layer
model.add(Flatten()) #Flatten layer
model.add(Dense(128,activation='relu')) #Fully connected layer
model.add(Dropout(0.5)) #Dropout layer
model.add(Dense(num_classes,activation='softmax')) #Output layer

#Model Compilation
model.compile(loss=keras.losses.categorical_crossentropy, optimizer=keras.optimizers.Adadelta(),metrics=['accuracy'])

In [16]:
#Training the Model
model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, verbose=1, validation_data=(x_test,y_test))
score = model.evaluate(x_test,y_test,verbose=0)

Epoch 1/3
469/469 [==============================] - 52s 111ms/step - loss: 2.2904 - accuracy: 0.1266 - val_loss: 2.2572 - val_accuracy: 0.3170
Epoch 2/3
469/469 [==============================] - 53s 112ms/step - loss: 2.2393 - accuracy: 0.2488 - val_loss: 2.1949 - val_accuracy: 0.5405
Epoch 3/3
469/469 [==============================] - 52s 111ms/step - loss: 2.1719 - accuracy: 0.3672 - val_loss: 2.1070 - val_accuracy: 0.6153


In [17]:
display(model.summary())

#32: no. of feature maps, 26*26 = (32-5+1)*(32-5+1), no. of params = 32*3*3+32 = 320
#Flatten 1: 12*12*64 = 9216
#dense 1179776 = 9216*128+128
#dense_3 1290 = 128*10+10+10

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 26, 26, 32)        320       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 24, 24, 64)        18496     
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 12, 12, 64)        0         
_________________________________________________________________
dropout (Dropout)            (None, 12, 12, 64)        0         
_________________________________________________________________
flatten (Flatten)            (None, 9216)              0         
_________________________________________________________________
dense (Dense)                (None, 128)               1179776   
_________________________________________________________________
dropout_1 (Dropout)          (None, 128)               0

None

In [18]:
#Predicting Thing
kr_test_pred = model.predict(x_test)

display(kr_test_pred.shape)
display(kr_test_pred[0].shape)
display(kr_test_pred[0])

(10000, 10)

(10,)

array([0.11079916, 0.08414773, 0.09699183, 0.10237232, 0.09493547,
       0.08975861, 0.0923583 , 0.12100884, 0.09198969, 0.11563796],
      dtype=float32)

In [19]:
#Finding the accuracy
import numpy as np

#View 1st 20 - both predicted & actual
np.argmax(kr_test_pred,axis=1)[:25] #argmax gives the position of highest number in a list


array([7, 2, 1, 0, 9, 1, 9, 6, 6, 9, 0, 0, 9, 0, 1, 0, 9, 0, 6, 9, 9, 6,
       6, 6, 9], dtype=int64)

In [20]:
np.argmax(y_test,axis=1)[:25] #argmax gives the position of highest number in a list

array([7, 2, 1, 0, 4, 1, 4, 9, 5, 9, 0, 6, 9, 0, 1, 5, 9, 7, 3, 4, 9, 6,
       6, 5, 4], dtype=int64)

In [21]:
#How many mismatches?
(np.argmax(kr_test_pred,axis=1)!=np.argmax(y_test,axis=1)).sum()

#Out of 10,000, 3847 are not matching. So, accuracy is not very good here.

3847

In [22]:
#Save our model
model.save('final_mnist.h5')